name: Trigger update aryailia.github.io github action
on:
  push:
    # Github actions use GITHUB_TOKEN which prevents recursively triggering workflows
    # See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
    branches: [compiled]
jobs:
  trigger_website_update:
    runs-on: ubuntu-latest
    steps:
      - name: Repository dispatch to website repo
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.UPDATE_PAT_TOKEN }}" \
          https://api.github.com/repos/Aryailia/aryailia.github.io/dispatches \
          -d '{"event_type":"Update from a-bas-le-ciel-data"}'
