name: Video metadata weekly download
on:
  schedule:
    - cron: "0 13 * * 6"  # Once a week on Sunday at 13:00

jobs:
  download_new_videos:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning master -> vm "./"
        uses: actions/checkout@v2  # From the marketplace, by GitHub

      - name: Verify then add GitHub SSH key
        run: |
          [ "$( ssh-keyscan -t rsa github.com | tee github-key-temp | ssh-keygen -lf - 2>/dev/null )" \
          = "2048 SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8 github.com (RSA)" ] \
          || { printf "Invalid GitHub SSH key" >&2; exit 1; }
          mkdir ~/.ssh
          cat github-key-temp >>~/.ssh/known_hosts
          eval "$( ssh-agent -a "$SSH_AUTH_SOCKET" )"
          <<EOF ssh-add -
          ${{ secrets.RUNNER_PRIVATE_KEY }}
          EOF

      - name: Download updates, commit, and push
        env:
          SSH_AUTH_SOCKET: /tmp/ssh_agent.sock
        run: |
          sudo pip3 install youtube-dlc

          git config user.email "Bot@users.noreply.github.com"
          git config user.name "Continuous Integration Bot"
          /bin/sh make.sh cron
