name: Trigger update aryailia.github.io github action
on:
  push:
    # Github actions use GITHUB_TOKEN which prevents recursively triggering workflows
    # See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
    branches: [master]

jobs:
  trigger_website_update:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning master -> the vm's "./"
        uses: actions/checkout@v2  # From the marketplace, by GitHub

      - name: Compile to "./publish"
        run: /bin/sh make.sh prepare-publish

      - name: Verify then add GitHub SSH key
        run: |
          [ "$( ssh-keyscan -t rsa github.com | tee github-key-temp | ssh-keygen -lf - 2>/dev/null )" \
          = "2048 SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8 github.com (RSA)" ] \
          || { printf "Invalid GitHub SSH key" >&2; exit 1; }
          mkdir ~/.ssh
          cat github-key-temp >>~/.ssh/known_hosts
          eval "$( ssh-agent -a "$SSH_AUTH_SOCKET" )"
          <<EOF ssh-add -
          ${{ secrets.RUNNER_PRIVATE_KEY }}
          EOF

      - name: Push to compiled branch
        env:
          SSH_AUTH_SOCKET: /tmp/ssh_agent.sock
        run: |
          rm .gitignore
          git add publish
          git config user.email "Bot@users.noreply.github.com"
          git config user.name "Continuous Integration Bot"
          git commit -m 'publishing public'
          git subtree split --prefix publish --branch compiled
          git push --force origin compiled

      - name: Repository dispatch to website repo
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.UPDATE_PAT_TOKEN }}" \
          https://api.github.com/repos/Aryailia/aryailia.github.io/dispatches \
          -d '{"event_type":"Update from a-bas-le-ciel-data"}'
